/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PatientFunction;

/**
 *
 * @author min
 */
public class Carte_gui extends javax.swing.JFrame {
    PatientFunction command = new PatientFunction();
    
    /**
     * Creates new form Carte_gui
     */
    public Carte_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(10000, 10000));
        setMinimumSize(new java.awt.Dimension(942, 692));
        setPreferredSize(new java.awt.Dimension(960, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"31", "1", "2", "3", "4", "5", "6"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"재첩국", "미역국","복어국","재첩국","된장국","소고기무국","만두국"},
                {"닭굴소스볶음", "버섯불고기","모듬장조림","매운소불고기","코다리찜","닭찜","돈김치찜"},
                {"감자채볶음", "어묵맛살볶음","오이양파무침","멸치아몬드볶음", "열무된장무침","쑥갓나물","호박새우젓볶음"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "햄채소볶음밥","백미밥","백미밥","백미밥","백미밥","카레밥"},
                {"아육국", "콩나물해장국","버섯들깨탕","감자양파국","순두부찌개","얼갈이된장국","매운무국"},
                {"갈치무조림", "애느타리무침","오징어볶음","고추장불고기","닭볶음탕","돈생강조림","탕수육"},
                {"도토리묵김치무침", "후식","영양부추무침","콩나물무침", "미역초무침","다시마채무침","후식"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","카레밥"},
                {"된장찌개", "알탕","들깨감자국","짬뽕국","부대찌개","얼큰닭곰탕","대구매운탕"},
                {"달갈말이", "꽁치감자조림","낚지볶음","고등어양념구이","가자미구이","두부조림","동그랑땡"},
                {"브로콜리초회", "상추겉절이","열무된장무침","미나리초무침", "오징어젓무침","잡채어묵볶음","가지나물"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
            },
            new String [] {
                "일", "월", "화", "수", "목", "금", "토"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 820, 370));

        jLabel1.setText("아침");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 40, -1));

        jLabel2.setText("점심");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 40, -1));

        jLabel3.setText("저녁");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 40, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\close.png")); // NOI18N
        jButton1.setText("돌아가기");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 640, -1, -1));

        jLabel4.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("식단표");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 80, -1));

        jButton2.setText("6월 1주차");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jButton3.setText("6월 2주차");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jButton4.setText("6월 3주차");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jButton5.setText("6월 4주차");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jButton6.setText("7월 1주차");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jButton7.setText("7월 2주차");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        jButton8.setText("7월 3주차");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, -1, -1));

        jButton9.setText("7월 4주차");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));

        jLabel5.setText("상기 메뉴는 물품사정 및 기타 변동에 의해 바뀔수 있으니 양해하여 주시기 바랍니다.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 463, -1));

        jLabel6.setText("* 원산지표시 ( 쌀 - 국내산, 돼지고기 - 국내산, 쇠고기 -호주산, 닭고기,오리 - 국내산, 깍두기,석박지 - 국내산, 배추김치 - 배추,고추가루/국내산)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 800, -1));

        jLabel7.setText("계란,메추리알 - 국내산. 육류가공품 ( 쇠고기 - 호주산, 돼지고기 - 국내산, 닭고기 -국내산 ). 베이컨 (돼지고기 - 수입산). 낙지 - 베트남, 중국산");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 766, -1));

        jLabel8.setText("미꾸라지 - 중국산 . 고등어 - 국내산 . 명태(코다리, 동태) - 러시아산 . 갈치 - 수입산 (모로코, 파키스탄)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 584, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\background.PNG")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println("6월 1주차 식단표");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"31", "1", "2", "3", "4", "5", "6"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"재첩국", "미역국","복어국","재첩국","된장국","소고기무국","만두국"},
                {"닭굴소스볶음", "버섯불고기","모듬장조림","매운소불고기","코다리찜","닭찜","돈김치찜"},
                {"감자채볶음", "어묵맛살볶음","오이양파무침","멸치아몬드볶음", "열무된장무침","쑥갓나물","호박새우젓볶음"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "햄채소볶음밥","백미밥","백미밥","백미밥","백미밥","카레밥"},
                {"아육국", "콩나물해장국","버섯들깨탕","감자양파국","순두부찌개","얼갈이된장국","매운무국"},
                {"갈치무조림", "애느타리무침","오징어볶음","고추장불고기","닭볶음탕","돈생강조림","탕수육"},
                {"도토리묵김치무침", "후식","영양부추무침","콩나물무침", "미역초무침","다시마채무침","후식"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","카레밥"},
                {"된장찌개", "알탕","들깨감자국","짬뽕국","부대찌개","얼큰닭곰탕","대구매운탕"},
                {"달갈말이", "꽁치감자조림","낚지볶음","고등어양념구이","가자미구이","두부조림","동그랑땡"},
                {"브로콜리초회", "상추겉절이","열무된장무침","미나리초무침", "오징어젓무침","잡채어묵볶음","가지나물"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
            },
            new String [] {
                "일", "월", "화", "수", "목", "금", "토"
            }
        ));

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.out.println("6월 2주차 식단표");
                      
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"7", "8", "9", "10", "11", "12", "13"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"얼갈이된장국", "재첩국","만두국","콩나물국","소고기탕국","북어국","감자양파국"},
                {"갈치무조링", "모듬장조림","코다리찜","매운소고기볶음","동그랑땡전","닭찜","버섯불고기"},
                {"진미채무침", "건새우볶음","미역줄기초무침","애느타리무침", "건취나물볶음","쑥갓나물","깻잎지"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "주먹밥","백미밥","백미밥","강된장비빔밥","백미밥","백미밥"},
                {"부대찌개", "잔치국수","근대국","홍합미역국","무들깨국","소고기고추장찌개","김치찌개"},
                {"돈불고기", "생선까스","돈찹스테이크","고등어조림","비엔나채소볶음","스팸깻잎전","삼치데리야끼구이"},
                {"상추/쌈장", "양배추샐러드","김구이/양념간장","미나리초무침", "김자반","상추겉절이","오이무침"},
                {"깍두기", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "깍두기"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"알탕", "소고기국","매운어묵국","아육국","매운닭곰탕","순두부찌개","대구탕"},
                {"김달갈말이", "두부조림","닭볶음탕","낙지볶음","가자미카레구이","고추장불고기","잡채"},
                {"다시마채무침", "꽈리초멸치볶음","숙주나물","우엉조림", "도라지초무침","콩나물맛살냉채","열무된장무침"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
            },
            new String [] {
                "일", "월", "화", "수", "목", "금", "토"
            }
        ));

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.out.println("6월 3주차 식단표");
         jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"14", "15", "16", "17", "18", "19", "20"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"들깨감자국", "동태국","소고기국","북어국","유부팽이된장국","만두국","호박새우젓탕"},
                {"소불고기", "모듬장조림","조기구이","코다리찜","매운소고기볶음","가자미무조림","낚지볶음"},
                {"숙주나물", "호박새우젓볶음","쑥갓나물","동부묵초무침", "감자채볶음","숙주나물무침","버섯초무침"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "콩나물밥","백미밥","백미밥","고추잡채/꽃빵","백미밥","백미밥"},
                {"얼갈이된장국", "재첩국","순두부찌개","오이냉국","부추달걀국","소고기고추장찌개","알탕"},
                {"갈치조림", "너비아니구이","닭찜","고추장불고기","만두탕수","잡채","돈생강조림"},
                {"멸치볶음", "떡볶이","구운채소샐러드","콩나물무침", "짜사이채무침","김자반","가지나물"},
                {"배추김치", "깍두기", "깍두기", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"짬뽕국", "두부고추장찌개","아육국","근대된장국","얼큰닭곰탕","김치찌개","미더덕된장찌개"},
                {"달걀말이", "고등어카레구이","동그랑땡전","오징어볶음","두부조림","삼치데리야끼구이","닭볶음탕"},
                {"어묵맛살볶음", "오이무침","미나리초무침","꽈리고추멸치볶음", "우엉조림","어묵꽈리초조림","상추겉절이"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "깍두기", "배추김치"},
            },
            new String [] {
                "일", "월", "화", "수", "목", "금", "토"
            }
        ));
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.out.println("6월 4주차 식단표");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"21", "22", "23", "24", "25", "26", "27"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"얼갈이된장국", "만두국","근대된장국","북어국","아육된장국","어묵국","재첩국"},
                {"감자채볶음", "코다리조림","매운소불고기","오징어볶음","꽁치감자조림","닭카레볶움","돈불고기"},
                {"미나리초무침", "멸치볶음","다시마채무침","열무된장무침", "진미채무침","도라지초무침","마늘쫑장아찌"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "햄채소볶음밥","백미밥","백미밥","유부초밥","백미밥","백미밥"},
                {"소고기무국", "김치콩나물국","다슬기탕","우무냉국","잔치국수","새알미역국","미더덕된장찌개"},
                {"너비아니", "순대,양파/쌈장","고추장불고기","닭볶음탕","오징어초무침","두부김치","낙지볶음"},
                {"쑥갓나물", "김자반","옥수수샐러드","아삭고추된장무침", "웨지감자/소스","콩나물무침","멸치볶음"},
                {"배추김치", "깍두기", "배추김치", "배추김치", "깍두기", "깍두기", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"얼큰닭곰탕", "강된장찌개","순두부찌개","김치찌개","알탕","소고기고추장찌개","짬뽕밥"},
                {"두부조림", "가자미구이","동그랑땡전","갈치구이","달걀말이","잡채","고등어무조림"},
                {"건새우마늘종볶음", "상추대파채무침","우엉곤약조림","무말랭이지", "콩나물맛살냉채","오징어젓무침","상추겉절이"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
            },
            new String [] {
                "일", "월", "화", "수", "목", "금", "토"
            }
        ));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.out.println("7월 1주차 식단표");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"28", "29", "30", "1", "2", "3", "4"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"얼갈이된장국", "알탕","소고기탕국","북어국","아육된장국","콩나물국","재첩국"},
                {"두부조림", "동그랑땡전","코다리찜","버섯불고기","모듬장조림","갈치무조림","낙지볶음"},
                {"달걀부추볶음", "양배추파채무침","애느타리무침","숙주나물", "건새우마늘종볶음","호박된장무침","무말랭이지"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "주먹밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"소고기고추장찌개", "유부된장국","버섯들깨탕","부대찌개","오이냉국","대구매운탕","근대국"},
                {"닭찜", "쫄면/삶은달걀","돈찹스테이크","가자미구이","너비아니구이","스팸깻잎전","닭볶음탕"},
                {"쑥갓나물", "생선까스","부추겉절이","미나리초무침", "후식","멸치볶음","상추겉절이"},
                {"배추김치", "배추김치", "배추김치", "깍두기", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"김치찌개", "꽁치추어탕","순두부찌개","다슬기탕","소고기들깨탕","짬뽕국","미더덕된장찌개"},
                {"삼치데리야끼구이", "돈불고기","김달걀말이","오징어볶음","돈김치찜","잡채","조기구이"},
                {"어묵조림", "오이무침","연근곤약조림","깻잎순나물", "버섯굴소스볶음","어묵볶음","오징어젓무침"},
                {"깍두기", "배추김치", "배추김치", "배추김치", "깍두기", "배추김치", "배추김치"},
            },
            new String [] {
                "일", "월", "화", "수", "목", "금", "토"
            }
        ));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         System.out.println("7월 2주차 식단표");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"5", "6", "7", "8", "9", "10", "11"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"얼갈이된장국", "북어국","만두국","근대국","소고기탕국","재첩국","콩나물국"},
                {"코다리찜", "매운소불고기","모듬장조림","동그랑땡전","갈치무조림","낙지볶음","닭찜"},
                {"오이도라지초무침", "양배추초무침","애느타리무침","감자꽈리초무침", "버섯초무침","숙주나물","김자반"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "녹두밥","백미밥","백미밥","열무비빔밥","백미밥","백미밥"},
                {"소고기미역국", "닭백숙","아육국","다슬기탕","오이냉국","김치찌개","미더덕된장찌개"},
                {"소시지볶음", "오징어젓무침","돈불고기","버섯불고기","메추리알장조림","조기구이","꽁치감자조림"},
                {"감자조림", "후식","상추/쌈장","멸치볶음", "후식","참나물무침","오이도라지초무침"},
                {"배추김치", "깍두기", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"꽁치추어탕", "강된장찌개","부대찌개","알탕","오징어무국","유부팽이된장","짬뽕국"},
                {"두부조림", "가자미카레구이","닭볶음탕","달걀말이","돈김치찜","고추장불고기","잡채"},
                {"잡채어묵볶음", "쑥갓나물","우엉조림", "미나리초무침", "양배추쌈/쌈장","버섯굴소스볶음","달걀부추볶음"},
                {"배추김치", "배추김치", "깍두기", "배추김치", "깍두기", "배추김치", "배추김치"},
            },
            new String [] {
                "일", "월", "화", "수", "목", "금", "토"
            }
        ));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.out.println("7월 3주차 식단표");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12", "13", "14", "15", "16", "17", "18"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"근대된장국", "소고기미역국","복어국","얼갈이된장국","들깨감자국","대구매운탕","재첩국"},
                {"모듬장조림", "코다리찜","소버섯불고기","낙지볶음","가자미무조림","돈생강조림","매운소고기볶음"},
                {"감자조림", "콩나물무침","마늘쫑조림", "오이부추겉절이", "양배추초무침","김자반","상추겉절이"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "마파두부덮밥","백미밥","백미밥","주먹밥","백미밥","백미밥"},
                {"알탕", "도토리묵국","근대국","콩나물국","냉모밀국수","오징어무국","호박새우젓국"},
                {"고추장불고기", "계란장","고등어무조림","스팸구이","생선까스","잡채","갈치무조림"},
                {"어묵조림", "후식","멸치볶음", "가지나물", "후식","얼갈이된장무침","오징어젓무침"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "깍두기", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","녹두밥","백미밥","백미밥"},
                {"순두부찌개", "아육국","얼큰닭곰탕","참찌김치찌개","닭죽","부대찌개","다슬기탕"},
                {"김달걀말이", "닭볶음탕","쫄면/삶은달걀","돈불고기","두부조림","동그랑땡전","닭찜"},
                {"다시마채무침", "깻잎순나물","미트볼채소볶음", "청경채굴소스볶음", "잡채어묵볶음","참나물무침","미나리초무침"},
                {"배추김치", "배추김치", "배추김치", "깍두기", "배추김치", "배추김치", "배추김치"},
            },
            new String [] {
                "일", "월", "화", "수", "목", "금", "토"
            }
        ));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        System.out.println("7월 4주차 식단표");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"19", "20", "21", "22", "23", "24", "25"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"아육국", "대구매운탕","근대된장국","재첩국","북어국","얼갈이된장국","유부된장국"},
                {"돈김치찜", "모듬장조림","소불고기","갈치무조림","두부조림","코다리찜","닭찜"},
                {"버섯매운볶음", "가지나물","오이도라지초무침", "상추겉절이", "감자채볶음","무말랭이지","김자반"},
                {"깍두기", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "비빔밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"소고기미역국", "오이냉국","다슬기탕","아육국","콩나물냉국","짬뽕국","호박새우젓국"},
                {"오징어볶음", "비엔나채소볶음","닭갈비","고추장불고기","고추잡채/꽃빵","버섯불고기","낙지볶음"},
                {"멸치볶음", "후식","청경채굴소스볶음", "오이무침", "떡볶이","오이,풋고추/쌈장","상추겉절이"},
                {"배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치", "배추김치"},
                {null, null, null, null, null, null, null},
                {"백미밥", "백미밥","백미밥","백미밥","백미밥","백미밥","백미밥"},
                {"순두부찌개", "만두국","소고기고추장찌개","부대찌개","알탕","김치찌개","꽁치추어탕"},
                {"달걀말이", "고등어무조림","가자미카레구이","동그랑땡전","잡채","삼치데리야끼구이","돈불고기"},
                {"아삭고추된장무침", "우엉곤약조림","숙주나물", "미역줄기버섯볶음", "참나물무침","어묵조림","오이무침"},
                {"배추김치", "배추김치", "깍두기", "배추김치", "배추김치", "깍두기", "배추김치"},
            },
            new String [] {
                "일", "월", "화", "수", "목", "금", "토"
            }
        ));
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carte_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carte_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carte_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carte_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carte_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
