package PatientFunction;

import Login.LoginSystem;
import Login.Login_gui;
import PatientFunction.PatientFunction;
import javax.swing.JOptionPane;

/**
 *
 * @author min
 */
public class PatientFunction_gui extends javax.swing.JFrame {

    LoginSystem system = new LoginSystem();
    PatientFunction command = new PatientFunction();

    /**
     * Creates new form PatientFunction_gui
     */
    public PatientFunction_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        duty = new javax.swing.JButton();
        call = new javax.swing.JButton();
        carte = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        duty.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\doctor.png")); // NOI18N
        duty.setText("당직표 확인");
        duty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dutyMouseClicked(evt);
            }
        });
        duty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dutyActionPerformed(evt);
            }
        });
        getContentPane().add(duty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 243, -1, 80));

        call.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\nurse.png")); // NOI18N
        call.setText("간호사 호출");
        call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callActionPerformed(evt);
            }
        });
        getContentPane().add(call, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 243, -1, 80));

        carte.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\building.png")); // NOI18N
        carte.setText("식단표 확인");
        carte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carteActionPerformed(evt);
            }
        });
        getContentPane().add(carte, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, 80));

        exit.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\logout.png")); // NOI18N
        exit.setText("로그아웃");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 503, 161, 80));

        jLabel1.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("환자 서비스");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\background.PNG")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dutyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dutyActionPerformed
        Duty duty = new Duty("당직표");
        Command nightDutyCommand = new NightDutyCommand(duty);
        command.setCommand(2, nightDutyCommand);
        command.executeCommand(2);
    }//GEN-LAST:event_dutyActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        system.isLogout();
        setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private void dutyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dutyMouseClicked

    }//GEN-LAST:event_dutyMouseClicked

    private void carteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carteActionPerformed
        Carte carte = new Carte("식단표");
        Command hospitalCarteCommand = new HospitalCarteCommand(carte);
        command.setCommand(0, hospitalCarteCommand);
        command.executeCommand(0);
    }//GEN-LAST:event_carteActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked

    }//GEN-LAST:event_exitMouseClicked

    private void callActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callActionPerformed
        // TODO add your handling code here:
        Call nurseCall = new Call("간호사");
        Command nurseCallCommand = new NurseCallCommand(nurseCall);
        command.setCommand(1, nurseCallCommand);
        command.executeCommand(1);

    }//GEN-LAST:event_callActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientFunction_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientFunction_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientFunction_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientFunction_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientFunction_gui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton call;
    private javax.swing.JButton carte;
    private javax.swing.JButton duty;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
