/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PatientCare;

import Login.DBConnector;
import java.sql.Connection;
import java.sql.Statement;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author user
 */
public class addPatient extends javax.swing.JFrame {
    PatientID pa_id =new PatientID();
    Name pa_name =new Name();
    DateOfBirth pa_dateofbirth =new DateOfBirth();
    Gender pa_gender =new Gender();
    BloodType pa_bloodtype =new BloodType();
    Address1 pa_address1 =new Address1();
    Address2 pa_address2 =new Address2();
    HomePhone pa_homephone =new HomePhone();
    CellPhone pa_cellphone =new CellPhone();
    Email pa_email =new Email();
    RemarkColumn pa_remarkcolumn =new RemarkColumn();
    RoomNumber pa_roomnum =new RoomNumber();
    WardPatientProfileFactory wa_fa = new WardPatientProfileFactory();
    /**
     * Creates new form addPatient
     */
    public addPatient() {
  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(942, 692));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 113, 96, -1));

        jTextField2.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 176, -1));

        jTextField3.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 176, -1));

        jComboBox1.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "C", "I" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 113, 68, -1));

        jComboBox2.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "남", "여" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 176, -1));

        jTextField4.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 176, -1));

        jTextField5.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 113, 231, -1));

        jTextField6.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 231, -1));

        jTextField7.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 231, -1));

        jTextField8.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 231, -1));

        jTextField10.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 455, 594, 174));

        jButton1.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\plus.png")); // NOI18N
        jButton1.setText("추가");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, -1, -1));

        jButton2.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\close.png")); // NOI18N
        jButton2.setText("종료");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, -1, -1));

        jLabel1.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel1.setText("환자ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 116, -1, -1));

        jLabel2.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel2.setText("이름");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel3.setText("생년월일");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel4.setText("성별");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel5.setText("혈액형");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel6.setText("주소");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 116, -1, -1));

        jLabel7.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel7.setText("상세주소");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel8.setText("연락처(자택)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel9.setText("연락처(휴대폰)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel10.setText("e-mail");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel11.setText("비고");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 455, -1, -1));

        jLabel12.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel12.setText("병실");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jTextField11.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 176, -1));

        jTextField9.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 231, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\background.PNG")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel14.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("환자 추가");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ide = (String)jComboBox1.getSelectedItem() + jTextField1.getText();
        String namee = jTextField2.getText();
        String dateofbirthe = jTextField3.getText();
        String gendere = (String)jComboBox2.getSelectedItem();
        String bloodtypee = jTextField4.getText();
        String address1e = jTextField5.getText();
        String address2e = jTextField6.getText();
        String homephonee = jTextField7.getText();
        String cellphonee = jTextField8.getText();
        String emaile = jTextField9.getText();
        String remarkcolumne = jTextField10.getText();
        String roomnum = jTextField11.getText();
        if(pa_id.idStorage(ide) && pa_name.nameStorage(namee) && pa_dateofbirth.dateofbirthStorage(dateofbirthe) && pa_gender.genderStorage(gendere) && pa_bloodtype.bloodtypeStorage(bloodtypee) && pa_address1.address1Storage(address1e) && pa_address2.address2Storage(address2e) && pa_homephone.homephoneStorage(homephonee) && pa_cellphone.cellphoneStorage(cellphonee) && pa_email.emailStorage(emaile) && pa_remarkcolumn.remarkcolumnStorage(remarkcolumne) && pa_roomnum.roomnumStorage(roomnum)){
            wa_fa.createPatientID(pa_id);
            wa_fa.createRoomNumber(pa_roomnum);
            wa_fa.createName(pa_name);
            wa_fa.createDateOfBirth(pa_dateofbirth);
            wa_fa.createGender(pa_gender);
            wa_fa.createBloodType(pa_bloodtype);
            wa_fa.createAddress1(pa_address1);
            wa_fa.createAddress2(pa_address2);
            wa_fa.createHomePhone(pa_homephone);
            wa_fa.createCellPhone(pa_cellphone);
            wa_fa.createEmail(pa_email);
            wa_fa.createRemarkColumn(pa_remarkcolumn);
            wa_fa.sqlFuction();
        }
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
