/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WardManagement;
/**
 *
 * @author HyunSung <gus005479@daum.net>
 */
public class mWGUI extends javax.swing.JFrame {
    int WardNum;
    String RoomNum;
    /**
     * Creates new form mWGUI1
     */
    public mWGUI(int WardNum) {
        this.WardNum = WardNum;                
        initComponents();
        checkWard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPRoom105 = new javax.swing.JPanel();
        Room05 = new javax.swing.JLabel();
        jPRoom102 = new javax.swing.JPanel();
        Room02 = new javax.swing.JLabel();
        jPRoom103 = new javax.swing.JPanel();
        Room03 = new javax.swing.JLabel();
        jPRoom101 = new javax.swing.JPanel();
        Room01 = new javax.swing.JLabel();
        jPRoom104 = new javax.swing.JPanel();
        Room04 = new javax.swing.JLabel();
        jPRoom106 = new javax.swing.JPanel();
        Room06 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        jPRoom105.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPRoom105.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPRoom105MouseClicked(evt);
            }
        });

        Room05.setFont(new java.awt.Font("궁서체", 1, 18)); // NOI18N
        Room05.setText("xxx호실");

        javax.swing.GroupLayout jPRoom105Layout = new javax.swing.GroupLayout(jPRoom105);
        jPRoom105.setLayout(jPRoom105Layout);
        jPRoom105Layout.setHorizontalGroup(
            jPRoom105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoom105Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Room05)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPRoom105Layout.setVerticalGroup(
            jPRoom105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoom105Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Room05)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jPRoom102.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPRoom102.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPRoom102MouseClicked(evt);
            }
        });

        Room02.setFont(new java.awt.Font("궁서체", 1, 18)); // NOI18N
        Room02.setText("xxx호실");

        javax.swing.GroupLayout jPRoom102Layout = new javax.swing.GroupLayout(jPRoom102);
        jPRoom102.setLayout(jPRoom102Layout);
        jPRoom102Layout.setHorizontalGroup(
            jPRoom102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoom102Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Room02)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPRoom102Layout.setVerticalGroup(
            jPRoom102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoom102Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Room02)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPRoom103.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPRoom103.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPRoom103MouseClicked(evt);
            }
        });

        Room03.setFont(new java.awt.Font("궁서체", 1, 18)); // NOI18N
        Room03.setText("xxx호실");

        javax.swing.GroupLayout jPRoom103Layout = new javax.swing.GroupLayout(jPRoom103);
        jPRoom103.setLayout(jPRoom103Layout);
        jPRoom103Layout.setHorizontalGroup(
            jPRoom103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoom103Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Room03)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPRoom103Layout.setVerticalGroup(
            jPRoom103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoom103Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Room03)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jPRoom101.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPRoom101.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPRoom101MouseClicked(evt);
            }
        });

        Room01.setFont(new java.awt.Font("궁서체", 1, 18)); // NOI18N
        Room01.setText("xxx호실");

        javax.swing.GroupLayout jPRoom101Layout = new javax.swing.GroupLayout(jPRoom101);
        jPRoom101.setLayout(jPRoom101Layout);
        jPRoom101Layout.setHorizontalGroup(
            jPRoom101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoom101Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Room01)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPRoom101Layout.setVerticalGroup(
            jPRoom101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoom101Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Room01)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPRoom104.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPRoom104.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPRoom104MouseClicked(evt);
            }
        });

        Room04.setFont(new java.awt.Font("궁서체", 1, 18)); // NOI18N
        Room04.setText("xxx호실");

        javax.swing.GroupLayout jPRoom104Layout = new javax.swing.GroupLayout(jPRoom104);
        jPRoom104.setLayout(jPRoom104Layout);
        jPRoom104Layout.setHorizontalGroup(
            jPRoom104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoom104Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Room04)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPRoom104Layout.setVerticalGroup(
            jPRoom104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoom104Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Room04)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPRoom106.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPRoom106.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPRoom106MouseClicked(evt);
            }
        });

        Room06.setFont(new java.awt.Font("궁서체", 1, 18)); // NOI18N
        Room06.setText("xxx호실");

        javax.swing.GroupLayout jPRoom106Layout = new javax.swing.GroupLayout(jPRoom106);
        jPRoom106.setLayout(jPRoom106Layout);
        jPRoom106Layout.setHorizontalGroup(
            jPRoom106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoom106Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Room06)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPRoom106Layout.setVerticalGroup(
            jPRoom106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoom106Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Room06)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPRoom104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPRoom101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPRoom105, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPRoom102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPRoom103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPRoom106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPRoom103, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPRoom102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPRoom101, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPRoom105, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPRoom104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPRoom106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jButton1.setText("뒤로가기");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPRoom101MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPRoom101MouseClicked
        RoomNum = Room01.getText();
        new mWInGUI(RoomNum).setVisible(true);
    }//GEN-LAST:event_jPRoom101MouseClicked

    private void jPRoom102MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPRoom102MouseClicked
        RoomNum = Room02.getText();
        new mWInGUI(RoomNum).setVisible(true);
    }//GEN-LAST:event_jPRoom102MouseClicked

    private void jPRoom103MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPRoom103MouseClicked
        RoomNum = Room03.getText();
        new mWInGUI(RoomNum).setVisible(true);
    }//GEN-LAST:event_jPRoom103MouseClicked

    private void jPRoom104MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPRoom104MouseClicked
        RoomNum = Room04.getText();
        new mWInGUI(RoomNum).setVisible(true);
    }//GEN-LAST:event_jPRoom104MouseClicked

    private void jPRoom105MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPRoom105MouseClicked
        RoomNum = Room05.getText();
        new mWInGUI(RoomNum).setVisible(true);
    }//GEN-LAST:event_jPRoom105MouseClicked

    private void jPRoom106MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPRoom106MouseClicked
        RoomNum = Room06.getText();
        new mWInGUI(RoomNum).setVisible(true);
    }//GEN-LAST:event_jPRoom106MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mWGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mWGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mWGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mWGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new mWGUI1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Room01;
    private javax.swing.JLabel Room02;
    private javax.swing.JLabel Room03;
    private javax.swing.JLabel Room04;
    private javax.swing.JLabel Room05;
    private javax.swing.JLabel Room06;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPRoom101;
    private javax.swing.JPanel jPRoom102;
    private javax.swing.JPanel jPRoom103;
    private javax.swing.JPanel jPRoom104;
    private javax.swing.JPanel jPRoom105;
    private javax.swing.JPanel jPRoom106;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    public void checkWard(){
        if(WardNum == 1){
            Room01.setText("101호실");
            Room02.setText("102호실");
            Room03.setText("103호실");
            Room04.setText("104호실");
            Room05.setText("105호실");
            Room06.setText("106호실");
        }
        else if(WardNum == 2){
            Room01.setText("201호실");
            Room02.setText("202호실");
            Room03.setText("203호실");
            Room04.setText("204호실");
            Room05.setText("205호실");
            Room06.setText("206호실");
        }
        else if(WardNum == 3){
            Room01.setText("301호실");
            Room02.setText("302호실");
            Room03.setText("303호실");
            Room04.setText("304호실");
            Room05.setText("305호실");
            Room06.setText("306호실");
        }
    }
}

