/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WardManagement;

import java.awt.Color;
/**
 *
 * @author HyunSung <gus005479@daum.net>
 */
public class WardSystem extends javax.swing.JFrame {
    boolean b_MW, b_ICU, b_CW;
    
    /**
     * Creates new form WardSystem
     */
    public WardSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MWButton = new javax.swing.JButton();
        CWButton = new javax.swing.JButton();
        ICUButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MWButton.setFont(new java.awt.Font("굴림", 1, 48)); // NOI18N
        MWButton.setText("메인");
        MWButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MWButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MWButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MWButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 120, 317, 144));

        CWButton.setFont(new java.awt.Font("굴림", 1, 48)); // NOI18N
        CWButton.setText("격리");
        CWButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CWButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CWButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CWButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 301, 317, 144));

        ICUButton.setFont(new java.awt.Font("굴림", 1, 48)); // NOI18N
        ICUButton.setText("중환자");
        ICUButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ICUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICUButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ICUButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 491, 317, 144));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\background.PNG")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MWButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MWButtonActionPerformed
        // TODO add your handling code here:
        new mainWardGUI().setVisible(true);
        System.out.println("메인병동 입니다.");
    }//GEN-LAST:event_MWButtonActionPerformed

    private void CWButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CWButtonActionPerformed
        // TODO add your handling code here:
        new ContainmentWardGUI().setVisible(true);
        System.out.println("격리병동 입니다.");
    }//GEN-LAST:event_CWButtonActionPerformed

    private void ICUButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICUButtonActionPerformed
        // TODO add your handling code here:
        new IntensiveCareUnitGUI().setVisible(true);
        System.out.println("중환자실 입니다.");
    }//GEN-LAST:event_ICUButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WardSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WardSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WardSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WardSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WardSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CWButton;
    private javax.swing.JButton ICUButton;
    private javax.swing.JButton MWButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
