/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReportSystem;

import javax.swing.JOptionPane;
/**
 *
 * @author HyunSung <gus005479@daum.net>
 */
public class ReportGUI extends javax.swing.JFrame {
    String name = null,birth = null,patientid = null,symptom = null, diagnosis = null, treatment = null, remark = null;
    /**
     * Creates new form ReportGUI
     */
    public ReportGUI(String name,String birth ,String symptom,String diagnosis,String treatment) {
        this.name = name;
        this.birth = birth;
        this.symptom = symptom;
        this.diagnosis = diagnosis;
        this.treatment = treatment;
        initComponents();
        JLPname.setText(name+"보고서");
        jLBirth1.setText(birth);
        jLSymptom.setText(symptom);
        jLDiag.setText(diagnosis);
        jLTreatment.setText(treatment);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JLPname = new javax.swing.JLabel();
        JLBirth = new javax.swing.JLabel();
        jLbel = new javax.swing.JLabel();
        JLBirth2 = new javax.swing.JLabel();
        JLBirth4 = new javax.swing.JLabel();
        jLBirth1 = new javax.swing.JLabel();
        jLDiag = new javax.swing.JLabel();
        jLSymptom = new javax.swing.JLabel();
        jLTreatment = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\icon.png")); // NOI18N
        jButton1.setText("인쇄");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 140, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\close.png")); // NOI18N
        jButton2.setText("뒤로가기");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        JLPname.setFont(new java.awt.Font("굴림", 1, 36)); // NOI18N
        JLPname.setText("환자 보고서");
        getContentPane().add(JLPname, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 43, -1, -1));

        JLBirth.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        JLBirth.setText("생년월일 :");
        getContentPane().add(JLBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLbel.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLbel.setText("진단결과 :");
        getContentPane().add(jLbel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        JLBirth2.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        JLBirth2.setText("증상       :");
        getContentPane().add(JLBirth2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        JLBirth4.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        JLBirth4.setText("처방전    :");
        getContentPane().add(JLBirth4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLBirth1.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLBirth1.setText("NULL");
        getContentPane().add(jLBirth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jLDiag.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLDiag.setText("NULL");
        getContentPane().add(jLDiag, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLSymptom.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLSymptom.setText("NULL");
        getContentPane().add(jLSymptom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        jLTreatment.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLTreatment.setText("NULL");
        getContentPane().add(jLTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\patient.png")); // NOI18N
        jButton3.setText("영수증");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Hospital\\image\\pay.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       PatientReport report = new PatientReport();
       report.print();
       JOptionPane.showMessageDialog(null, ("인쇄 완료."));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PatientReceipt receipt = new PatientReceipt();
        Report receiptAdapter = new ReceiptAdapter(receipt);
        receiptAdapter.print();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new ReportGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLBirth;
    private javax.swing.JLabel JLBirth2;
    private javax.swing.JLabel JLBirth4;
    private javax.swing.JLabel JLPname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLBirth1;
    private javax.swing.JLabel jLDiag;
    private javax.swing.JLabel jLSymptom;
    private javax.swing.JLabel jLTreatment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbel;
    // End of variables declaration//GEN-END:variables
}
